;override default config here

[pluginSystem]
disabled = false
communityDisabled = false

[keybindings.plugins.ai-shell-jf]
new-tab-dropdown-item = ctrlOrCmd+l

[keybindings.plugins.bks-ai-shell]
new-tab-dropdown-item = ""

[plugins.bks-ai-shell]
disabled = true

[plugins.ai-shell-jf]
disabled = false
